### ISSUE TITLE
[Suggestion] 1.19.4 support?

### ISSUE THREAD

**Issue by xleb-normal** [AntiCope/radialhud#1]
### Describe the feature

When you start Minecraft 1.19.4 with this mod and press the UI activation button, the game closes with an error

Are there plans to fix this?

**Comment by xleb-normal** [comment]
@C10udburst please port to version 1.20

**Comment by GoofyBoi420** [comment]
wut

**Comment by xleb-normal** [comment]
1.21 maybe...?
